# Global Config
SinatraPort: 9999
X_AUTOJMX_TOKEN: "AutoJMX_Token" # Header for Auth
DataBase_Connection: "postgres://postgres:root@localhost:5432/restjmeter"
JMX_File_DIR: "/Users/yanli6/Personal/DevDir/Code/rubymine/jmeter_auto_rest_service/test/" # Absolute dir path for jmx files
JMeter_Reside_OS: "OSX"
JMeter_Home: "/Users/yanli6/Personal/DevDir/DevTools/apache-jmeter-2.13"
Aggregate_Results_Dir: "/Users/yanli6/Personal/DevDir/Code/rubymine/jmeter_auto_rest_service/test/aggregate_results"